### ISSUE TITLE
different pressure sensor options?

### ISSUE THREAD

**Issue by Gubbledenut** [KOOPInstruments/teensycorder#1]
Could this work with a 5050 pressure sensor? it's not differential but I use it on another EWI Open woodwind project , works well?
Thanks

**Comment by ronfar623** [comment]
I can't say for sure never having used one, but if it works the same way, I don't see why it wouldn't.

If memory serves, the MPXV7002DP returns an analogRead value of around 512 (range 0-1023) at a neutral state.  My code just grabs this value at startup, and then any readings slightly above that will both trigger a note-on, and also map the level to MIDI CC 11 between 95 and 127 to give a bit of expression.

What's the part number?  It looks like there are a few variants.  If the dimensions are different, you would need to redesign the mouthpiece.  I also had to do a bit of trial and error printing with different mouth pieces to get the pressure at an appropriate level for the sensor's sensitivity.  Too narrow and there was zero range to play with, too much and you're constantly out of breath.

**Comment by Gubbledenut** [comment]
I'm using a MXP5010GP with a right angle valve as a moisture trap, I can easily adapt the mouthpiece.
it should just work..I'll make up a test rig on to try.
Thanks

**Comment by Gubbledenut** [comment]
Thank you I have got the 5010 to work but realise it has a higher pressure requirement, some 7020 on the way !
